from __future__ import annotations

from pathlib import Path

import pandas as pd

from RegimeTrading.core.paths import COLLECTOR_OUTPUT_DIR, DATA_DIR, POWERBI_WORKBOOK, REFERENCE_DATA_DIR, legacy_output_path


TABLES = {
    "regime_gap_recovery_summary": DATA_DIR / "regime_gap_recovery_summary.csv",
    "regime_gap_recovery_trades": DATA_DIR / "regime_gap_recovery_trades.csv",
    "regime_gap_recovery_daily": DATA_DIR / "regime_gap_recovery_daily.csv",
    "regime_gap_recovery_latest": DATA_DIR / "regime_gap_recovery_latest.csv",
    "regime_gap_recovery_candidates": DATA_DIR / "regime_gap_recovery_candidates.csv",
    "regime_gap_recovery_forward_summary": DATA_DIR / "regime_gap_recovery_forward_summary.csv",
    "regime_gap_recovery_forward_trades": DATA_DIR / "regime_gap_recovery_forward_trades.csv",
    "regime_gap_recovery_forward_daily": DATA_DIR / "regime_gap_recovery_forward_daily.csv",
    "regime_gap_recovery_forward_candidates": DATA_DIR / "regime_gap_recovery_forward_candidates.csv",
    "nasdaq_yahoo_decision_summary": COLLECTOR_OUTPUT_DIR / "nasdaq_yahoo_strategy_decision_summary.csv",
    "nasdaq_yahoo_decision_detail": COLLECTOR_OUTPUT_DIR / "nasdaq_yahoo_strategy_decision_comparison.csv",
    "v1_validation_portfolio_summary": legacy_output_path("v1_validation_portfolio_summary.csv"),
    "v1_validation_portfolio_trade_ledger": legacy_output_path("v1_validation_portfolio_trade_ledger.csv"),
    "v1_validation_portfolio_equity_curve": legacy_output_path("v1_validation_portfolio_equity_curve.csv"),
    "v1_validation_portfolio_daily": legacy_output_path("v1_validation_portfolio_daily.csv"),
    "v1_validation_concentration_summary": legacy_output_path("v1_validation_concentration_summary.csv"),
    "v1_validation_concentration_scenarios": legacy_output_path("v1_validation_concentration_scenarios.csv"),
    "v1_validation_contribution_detail": legacy_output_path("v1_validation_contribution_detail.csv"),
    "v1_validation_leave_one_out": legacy_output_path("v1_validation_leave_one_out.csv"),
    "v1_exec_stress_summary": legacy_output_path("v1_validation_execution_stress_summary.csv"),
    "v1_exec_stress_scenarios": legacy_output_path("v1_validation_execution_stress_scenarios.csv"),
    "v1_exec_stress_trade_detail": legacy_output_path("v1_validation_execution_stress_trade_detail.csv"),
    "v1_exec_cost_curve": legacy_output_path("v1_validation_execution_cost_curve.csv"),
    "v1_parameter_robust_summary": legacy_output_path("v1_validation_parameter_robustness_summary.csv"),
    "v1_parameter_robust_scenarios": legacy_output_path("v1_validation_parameter_robustness_scenarios.csv"),
    "v1_parameter_sensitivity": legacy_output_path("v1_validation_parameter_sensitivity.csv"),
    "v1_parameter_baseline_recon": legacy_output_path("v1_validation_parameter_baseline_reconciliation.csv"),
    "v1_provider_quality_summary": legacy_output_path("v1_validation_provider_quality_summary.csv"),
    "v1_provider_session_detail": legacy_output_path("v1_validation_provider_session_detail.csv"),
    "v1_provider_daily_summary": legacy_output_path("v1_validation_provider_daily_summary.csv"),
    "v1_provider_mismatch_detail": legacy_output_path("v1_validation_provider_mismatch_detail.csv"),
    "v1_exposure_efficiency_summary": legacy_output_path("v1_validation_exposure_efficiency_summary.csv"),
    "v1_exposure_position_detail": legacy_output_path("v1_validation_exposure_position_detail.csv"),
    "v1_exposure_interval_detail": legacy_output_path("v1_validation_exposure_interval_detail.csv"),
    "v1_exposure_daily": legacy_output_path("v1_validation_exposure_daily.csv"),
    "v1_position_size_scenarios": legacy_output_path("v1_validation_position_size_scenarios.csv"),
    "v1_exposure_reconciliation": legacy_output_path("v1_validation_exposure_reconciliation.csv"),
    "regime_feature_foundation_summary": DATA_DIR / "regime_feature_foundation_summary.csv",
    "regime_daily_features": DATA_DIR / "regime_daily_features.csv",
    "regime_feature_definitions": DATA_DIR / "regime_feature_definitions.csv",
    "regime_feature_completeness": DATA_DIR / "regime_feature_completeness.csv",
    "regime_point_in_time_audit": DATA_DIR / "regime_point_in_time_audit.csv",
    "regime_v1_timing_summary": DATA_DIR / "regime_v1_timing_comparison_summary.csv",
    "regime_v1_timing_daily": DATA_DIR / "regime_v1_timing_comparison_daily.csv",
    "regime_v1_timing_candidates": DATA_DIR / "regime_v1_timing_comparison_candidates.csv",
    "regime_v1_timing_trades": DATA_DIR / "regime_v1_timing_comparison_trades.csv",
    "regime_taxonomy_summary": DATA_DIR / "regime_taxonomy_summary.csv",
    "regime_daily_taxonomy": DATA_DIR / "regime_daily_taxonomy.csv",
    "regime_taxonomy_definitions": DATA_DIR / "regime_taxonomy_definitions.csv",
    "regime_taxonomy_distribution": DATA_DIR / "regime_taxonomy_distribution.csv",
    "regime_taxonomy_transitions": DATA_DIR / "regime_taxonomy_transitions.csv",
    "regime_playbook_spec_summary": DATA_DIR / "regime_playbook_specification_summary.csv",
    "regime_playbook_registry": DATA_DIR / "regime_playbook_registry.csv",
    "regime_playbook_data_requirements": DATA_DIR / "regime_playbook_data_requirements.csv",
    "regime_playbook_session_coverage": DATA_DIR / "regime_playbook_session_coverage.csv",
    "regime_playbook_baseline_summary": DATA_DIR / "regime_playbook_baseline_summary.csv",
    "regime_playbook_baseline_sessions": DATA_DIR / "regime_playbook_baseline_sessions.csv",
    "regime_playbook_baseline_candidates": DATA_DIR / "regime_playbook_baseline_candidates.csv",
    "regime_playbook_baseline_trades": DATA_DIR / "regime_playbook_baseline_trades.csv",
    "regime_playbook_baseline_legs": DATA_DIR / "regime_playbook_baseline_trade_legs.csv",
    "regime_playbook_baseline_performance": DATA_DIR / "regime_playbook_baseline_performance.csv",
    "regime_playbook_baseline_audit": DATA_DIR / "regime_playbook_baseline_audit.csv",
    "regime_diag_summary": DATA_DIR / "regime_playbook_diagnostic_summary.csv",
    "regime_trade_diagnostics": DATA_DIR / "regime_playbook_trade_diagnostics.csv",
    "regime_playbook_diagnostics": DATA_DIR / "regime_playbook_diagnostics.csv",
    "regime_diag_slices": DATA_DIR / "regime_playbook_diagnostic_slices.csv",
    "regime_target_scenarios": DATA_DIR / "regime_playbook_target_scenarios.csv",
    "regime_cost_scenarios": DATA_DIR / "regime_playbook_cost_scenarios.csv",
    "regime_leave_one_day_out": DATA_DIR / "regime_playbook_leave_one_day_out.csv",
    "regime_pair_direction_controls": DATA_DIR / "regime_playbook_pair_direction_controls.csv",
    "regime_challenger_summary": DATA_DIR / "regime_challenger_matrix_summary.csv",
    "regime_challenger_registry": DATA_DIR / "regime_challenger_registry.csv",
    "regime_challenger_candidates": DATA_DIR / "regime_challenger_candidates.csv",
    "regime_challenger_trades": DATA_DIR / "regime_challenger_trades.csv",
    "regime_challenger_legs": DATA_DIR / "regime_challenger_trade_legs.csv",
    "regime_challenger_performance": DATA_DIR / "regime_challenger_performance.csv",
    "regime_challenger_rankings": DATA_DIR / "regime_challenger_rankings.csv",
    "regime_challenger_sessions": DATA_DIR / "regime_challenger_session_coverage.csv",
    "regime_challenger_audit": DATA_DIR / "regime_challenger_audit.csv",
    "instrument_taxonomy_summary": DATA_DIR / "instrument_taxonomy_summary.csv",
    "instrument_static_taxonomy": REFERENCE_DATA_DIR / "instrument_static_taxonomy.csv",
    "instrument_characteristic_definitions": REFERENCE_DATA_DIR / "instrument_characteristic_definitions.csv",
    "instrument_pit_characteristics": REFERENCE_DATA_DIR / "instrument_point_in_time_characteristics.csv",
    "instrument_group_daily_state": REFERENCE_DATA_DIR / "instrument_group_daily_state.csv",
    "instrument_taxonomy_completeness": DATA_DIR / "instrument_taxonomy_completeness.csv",
    "instrument_relationship_constraints": REFERENCE_DATA_DIR / "instrument_relationship_constraints.csv",
    "instrument_taxonomy_audit": DATA_DIR / "instrument_taxonomy_audit.csv",
    "regime_sector_strategy_summary": DATA_DIR / "regime_sector_strategy_summary.csv",
    "regime_sector_strategy_trade_ctx": DATA_DIR / "regime_sector_strategy_trade_context.csv",
    "regime_sector_strategy_leg_ctx": DATA_DIR / "regime_sector_strategy_leg_context.csv",
    "regime_sector_strategy_segments": DATA_DIR / "regime_sector_strategy_segment_performance.csv",
    "regime_sector_strategy_pairs": DATA_DIR / "regime_sector_strategy_pair_performance.csv",
    "regime_sector_strategy_exclusions": DATA_DIR / "regime_sector_strategy_exclusion_robustness.csv",
    "regime_sector_strategy_dim_audit": DATA_DIR / "regime_sector_strategy_dimension_audit.csv",
    "regime_sector_strategy_state_audit": DATA_DIR / "regime_sector_strategy_state_audit.csv",
    "regime_sector_strategy_rankings": DATA_DIR / "regime_sector_strategy_rankings.csv",
    "state_filter_summary": DATA_DIR / "regime_state_filtered_summary.csv",
    "state_filter_contracts": DATA_DIR / "regime_state_filtered_contract_registry.csv",
    "state_filter_sessions": DATA_DIR / "regime_state_filtered_session_coverage.csv",
    "state_filter_candidates": DATA_DIR / "regime_state_filtered_candidates.csv",
    "state_filter_trades": DATA_DIR / "regime_state_filtered_trades.csv",
    "state_filter_legs": DATA_DIR / "regime_state_filtered_trade_legs.csv",
    "state_filter_performance": DATA_DIR / "regime_state_filtered_performance.csv",
    "state_filter_comparisons": DATA_DIR / "regime_state_filtered_same_cohort_comparisons.csv",
    "state_filter_robustness": DATA_DIR / "regime_state_filtered_robustness.csv",
    "state_filter_multiple_tests": DATA_DIR / "regime_state_filtered_multiple_testing.csv",
    "state_filter_audit": DATA_DIR / "regime_state_filtered_audit.csv",
    "holdout_transport_summary": DATA_DIR / "regime_holdout_transport_summary.csv",
    "holdout_universe": REFERENCE_DATA_DIR / "regime_holdout_universe_registry.csv",
    "holdout_data_coverage": DATA_DIR / "regime_holdout_data_coverage.csv",
    "holdout_pit_characteristics": DATA_DIR / "regime_holdout_point_in_time_characteristics.csv",
    "holdout_group_state": DATA_DIR / "regime_holdout_group_daily_state.csv",
    "holdout_contracts": DATA_DIR / "regime_holdout_contract_registry.csv",
    "holdout_sessions": DATA_DIR / "regime_holdout_session_coverage.csv",
    "holdout_candidates": DATA_DIR / "regime_holdout_candidates.csv",
    "holdout_trades": DATA_DIR / "regime_holdout_trades.csv",
    "holdout_legs": DATA_DIR / "regime_holdout_trade_legs.csv",
    "holdout_performance": DATA_DIR / "regime_holdout_performance.csv",
    "holdout_comparisons": DATA_DIR / "regime_holdout_comparisons.csv",
    "holdout_robustness": DATA_DIR / "regime_holdout_robustness.csv",
    "holdout_multiple_tests": DATA_DIR / "regime_holdout_multiple_testing.csv",
    "holdout_audit": DATA_DIR / "regime_holdout_audit.csv",
}

for _table_name, _table_path in tuple(TABLES.items()):
    if _table_path.parent == DATA_DIR and (
        _table_path.name.startswith((
            "regime_gap_recovery_",
            "regime_v1_timing_comparison_",
            "regime_feature_",
            "regime_daily_features",
            "regime_point_in_time_",
            "regime_taxonomy_",
            "regime_playbook_",
            "regime_challenger_",
            "regime_sector_strategy_",
            "regime_state_filtered_",
            "regime_holdout_",
            "instrument_taxonomy_",
        ))
    ):
        TABLES[_table_name] = legacy_output_path(_table_path.name)

NUMERIC_COLUMNS = {
    "entry_price",
    "stop_price",
    "target_price",
    "exit_price",
    "current_price",
    "entry_trigger",
    "previous_close",
    "open_price",
    "risk_pct",
    "gap",
    "gap_pct",
    "opening_range_pct",
    "opening_range_pct_points",
    "risk_pct_points",
    "reward_risk",
    "distance_to_entry",
    "distance_to_target",
    "pnl_pct",
    "position_size_sek",
    "pnl_sek",
    "account_return",
    "total_account_return",
    "cumulative_account_return",
    "cumulative_pnl_sek",
    "trade_duration_minutes",
    "risk_per_share",
    "r_multiple_achieved",
    "win_rate",
    "profit_factor",
    "avg_r_multiple",
    "total_candidates",
    "valid_candidates",
    "triggered_candidates",
    "completed_trades",
    "wins",
    "losses",
    "total_pnl_sek",
    "gap_diff_bps",
    "open_price_diff_bps",
    "entry_trigger_diff_bps",
    "stop_price_diff_bps",
    "target_price_diff_bps",
    "exit_price_diff_bps",
    "pnl_diff_bps",
    "entry_time_diff_minutes",
    "ticker_day_rows",
    "setup_comparable_rows",
    "trigger_state_comparable_rows",
    "trigger_final_comparable_rows",
    "both_triggered_rows",
    "outcome_comparable_rows",
    "current_decision_class_match_rate",
    "invalid_reason_match_rate",
    "entry_trigger_within_1bp_rate",
    "stop_price_within_1bp_rate",
    "current_trigger_state_match_rate",
    "final_trigger_decision_match_rate",
    "entry_time_within_5m_rate",
    "exit_reason_match_rate",
    "overall_current_decision_match_rate",
    "initial_capital_sek",
    "position_size_pct",
    "position_size_sek",
    "max_open_positions",
    "input_trade_rows",
    "input_closed_trades",
    "input_open_trades",
    "selected_trade_rows",
    "selected_closed_trades",
    "selected_open_trades",
    "rejected_capacity_trades",
    "excluded_invalid_trades",
    "selection_rate",
    "max_open_positions_observed",
    "same_timestamp_ambiguous_groups",
    "days_with_capacity_rejections",
    "gross_profit_sek",
    "gross_loss_sek",
    "total_realized_pnl_sek",
    "final_realized_equity_sek",
    "total_realized_return",
    "max_drawdown",
    "all_trades_counterfactual_pnl_sek",
    "rejected_counterfactual_pnl_sek",
    "capacity_pnl_difference_sek",
    "source_trade_row",
    "source_net_pnl_pct",
    "source_position_size_sek",
    "model_position_size_sek",
    "entry_priority",
    "same_timestamp_entry_count",
    "available_slots_before_group",
    "active_positions_before_entry",
    "portfolio_pnl_sek",
    "portfolio_return_contribution",
    "equity_before_exit_sek",
    "equity_after_exit_sek",
    "event_number",
    "pnl_sek",
    "realized_equity_sek",
    "cumulative_pnl_sek",
    "cumulative_return",
    "running_peak_equity_sek",
    "drawdown",
    "open_positions_after_event",
    "selected_entries",
    "capacity_ambiguous_trades",
    "daily_realized_pnl_sek",
    "daily_realized_return_on_initial_capital",
    "cumulative_realized_pnl_sek",
    "end_realized_equity_sek",
    "end_cumulative_return",
    "scenario_order",
    "requested_exclusion_count",
    "actual_exclusion_count",
    "baseline_realized_pnl_sek",
    "excluded_baseline_selected_pnl_sek",
    "direct_subtraction_pnl_sek",
    "resimulated_pnl_sek",
    "replacement_effect_sek",
    "pnl_change_vs_baseline_sek",
    "retained_pnl_ratio",
    "added_selected_trade_count",
    "removed_selected_trade_count",
    "excluded_input_trade_count",
    "excluded_baseline_selected_closed_trades",
    "scenario_realized_pnl_sek",
    "fragility_rank_within_dimension",
    "rank_within_level",
    "trade_count",
    "positive_pnl_sek",
    "negative_pnl_sek",
    "net_pnl_share",
    "gross_profit_share",
    "cumulative_positive_profit_share",
    "baseline_selected_closed_trades",
    "baseline_gross_profit_sek",
    "baseline_gross_loss_sek",
    "baseline_profit_factor",
    "baseline_max_drawdown",
    "profitable_days",
    "losing_days",
    "largest_winner_sek",
    "largest_loser_sek",
    "top_1_trade_pnl_sek",
    "top_1_trade_net_pnl_share",
    "top_3_trade_pnl_sek",
    "top_3_trade_net_pnl_share",
    "top_5_trade_pnl_sek",
    "top_5_trade_net_pnl_share",
    "top_1_day_pnl_sek",
    "top_1_day_net_pnl_share",
    "top_3_day_pnl_sek",
    "top_3_day_net_pnl_share",
    "top_5_day_pnl_sek",
    "top_5_day_net_pnl_share",
    "positive_trade_concentration_hhi",
    "positive_day_concentration_hhi",
    "pnl_after_remove_top_1_trade_resim_sek",
    "pnl_after_remove_top_3_trades_resim_sek",
    "pnl_after_remove_top_5_trades_resim_sek",
    "pnl_after_remove_top_1_day_resim_sek",
    "pnl_after_remove_top_3_days_resim_sek",
    "pnl_after_remove_top_5_days_resim_sek",
    "worst_leave_one_out_pnl_sek",
    "leave_one_out_scenarios",
    "leave_one_out_profitable_scenarios",
    "baseline_total_cost_bps",
    "zero_cost_realized_pnl_sek",
    "gross_edge_before_costs_sek",
    "break_even_total_cost_bps",
    "highest_tested_profitable_cost_bps",
    "moderate_stress_pnl_sek",
    "moderate_stress_retained_pnl_ratio",
    "conservative_stress_pnl_sek",
    "conservative_stress_retained_pnl_ratio",
    "harsh_stress_pnl_sek",
    "harsh_stress_retained_pnl_ratio",
    "scenario_count",
    "profitable_scenario_count",
    "worst_scenario_pnl_sek",
    "total_cost_bps",
    "entry_slippage_bps",
    "market_exit_slippage_bps",
    "target_exit_slippage_bps",
    "source_entry_price",
    "source_exit_price",
    "stressed_entry_price",
    "stressed_exit_price",
    "reconstructed_source_gross_pnl_pct",
    "stressed_gross_pnl_pct",
    "stressed_net_pnl_pct",
    "net_pnl_change_pct",
    "applied_exit_slippage_bps",
    "stressed_portfolio_pnl_sek",
    "retained_pnl_ratio_vs_baseline",
    "distance_from_v1",
    "min_gap",
    "max_gap",
    "opening_range_minutes",
    "target_recovery_fraction",
    "max_risk_pct",
    "candidate_count",
    "valid_setup_count",
    "triggered_trade_count",
    "selected_trade_count",
    "pnl_change_vs_baseline_sek",
    "rank_by_pnl",
    "complete_session_dates",
    "excluded_incomplete_dates",
    "baseline_candidate_count",
    "baseline_triggered_trades",
    "baseline_rank_by_pnl",
    "baseline_percentile_by_pnl",
    "profitable_scenario_share",
    "one_at_a_time_scenario_count",
    "one_at_a_time_profitable_count",
    "one_at_a_time_profitable_share",
    "core_neighborhood_scenario_count",
    "core_neighborhood_profitable_count",
    "core_neighborhood_profitable_share",
    "core_neighborhood_median_pnl_sek",
    "core_neighborhood_p25_pnl_sek",
    "core_neighborhood_min_pnl_sek",
    "core_neighborhood_max_pnl_sek",
    "core_neighborhood_median_retained_pnl_ratio",
    "best_scenario_pnl_sek",
    "worst_scenario_pnl_sek",
    "median_realized_pnl_sek",
    "mean_realized_pnl_sek",
    "min_realized_pnl_sek",
    "max_realized_pnl_sek",
    "median_retained_pnl_ratio",
    "median_selected_closed_trades",
    "median_profit_factor",
    "median_max_drawdown",
    "research_ticker_count",
    "complete_ticker_count",
    "comparison_dates",
    "complete_eod_dates",
    "incomplete_dates",
    "setup_quality_eligible_rows",
    "final_trigger_quality_eligible_rows",
    "outcome_quality_eligible_rows",
    "setup_validity_match_rate",
    "trading_action_match_rate",
    "exact_diagnostic_match_rate",
    "stage_appropriate_high_quality_rows",
    "stage_appropriate_high_quality_rate",
    "full_window_provider_overlap_rate",
    "full_window_ohlc_within_1bp_rate",
    "mismatch_rows",
    "critical_mismatch_rows",
    "expected_regime_bars",
    "expected_entry_bars",
    "expected_full_bars",
    "yahoo_regime_bars",
    "nasdaq_regime_bars",
    "both_regime_bars",
    "yahoo_entry_bars",
    "nasdaq_entry_bars",
    "both_entry_bars",
    "yahoo_full_bars",
    "nasdaq_full_bars",
    "both_full_bars",
    "yahoo_regime_coverage_rate",
    "nasdaq_regime_coverage_rate",
    "both_regime_coverage_rate",
    "yahoo_entry_coverage_rate",
    "nasdaq_entry_coverage_rate",
    "both_entry_coverage_rate",
    "yahoo_full_coverage_rate",
    "nasdaq_full_coverage_rate",
    "both_full_coverage_rate",
    "regime_ohlc_within_1bp_rate",
    "entry_ohlc_within_1bp_rate",
    "full_ohlc_within_1bp_rate",
    "setup_ready_rows",
    "final_trigger_ready_rows",
    "final_outcome_ready_rows",
    "full_session_minutes",
    "study_calendar_days",
    "observed_research_sessions",
    "complete_observed_sessions",
    "incomplete_observed_sessions",
    "active_trading_days",
    "selected_position_count",
    "selected_closed_positions",
    "selected_open_positions",
    "max_deployable_capital_sek",
    "total_observed_strategy_hours",
    "total_position_hours",
    "closed_position_hours",
    "open_observed_position_hours",
    "position_session_equivalents",
    "capital_hours_sek",
    "average_deployed_capital_sek",
    "average_deployed_capital_active_days_sek",
    "maximum_deployed_capital_sek",
    "account_capital_utilization_rate",
    "active_day_account_utilization_rate",
    "slot_capacity_utilization_rate",
    "idle_cash_rate",
    "time_zero_positions_rate",
    "time_one_position_rate",
    "time_two_positions_rate",
    "realized_pnl_sek",
    "account_period_return",
    "return_on_average_deployed_capital",
    "return_on_maximum_deployed_capital",
    "average_realized_pnl_per_closed_trade_sek",
    "average_net_return_per_closed_trade",
    "realized_pnl_per_closed_position_hour_sek",
    "realized_pnl_per_active_trading_day_sek",
    "realized_pnl_per_observed_session_sek",
    "mechanical_annualized_account_return",
    "mechanical_annualized_return_on_average_deployed_capital",
    "exposure_minutes",
    "capital_minutes_sek",
    "realized_return_on_position_size",
    "interval_minutes",
    "open_positions",
    "deployed_capital_sek",
    "idle_cash_sek",
    "realized_equity_at_interval_start_sek",
    "cumulative_realized_pnl_at_interval_start_sek",
    "observed_strategy_minutes",
    "zero_position_minutes",
    "one_position_minutes",
    "two_position_minutes",
    "position_minutes",
    "fixed_position_size_sek",
    "position_size_pct_of_account",
    "max_two_slot_allocation_sek",
    "max_two_slot_allocation_rate",
    "scaled_realized_pnl_sek",
    "scaled_final_realized_equity_sek",
    "scaled_account_period_return",
    "scaled_max_drawdown",
    "scaled_average_deployed_capital_sek",
    "scaled_account_capital_utilization_rate",
    "pnl_tolerance_sek",
    "portfolio_summary_pnl_sek",
    "portfolio_ledger_closed_pnl_sek",
    "portfolio_equity_final_pnl_sek",
    "exposure_summary_pnl_sek",
    "exposure_position_closed_pnl_sek",
    "exposure_daily_pnl_sek",
    "position_size_baseline_pnl_sek",
    "max_absolute_pnl_difference_sek",
    "portfolio_summary_selected_closed",
    "portfolio_ledger_selected_closed",
    "exposure_summary_selected_closed",
    "exposure_position_selected_closed",
    "portfolio_summary_selected_open",
    "portfolio_ledger_selected_open",
    "exposure_summary_selected_open",
    "exposure_position_selected_open",
    "missing_exposure_trade_count",
    "extra_exposure_trade_count",
    "duplicate_exposure_trade_count",
    "universe_ticker_count",
    "observed_ticker_count",
    "prior_close_ticker_count",
    "opening_ticker_count",
    "strict_cutoff_ticker_count",
    "valid_cross_section_ticker_count",
    "expected_early_bar_count_total",
    "observed_early_bar_count_total",
    "early_bar_coverage_rate",
    "gap_up_breadth",
    "gap_down_breadth",
    "flat_gap_breadth",
    "mean_gap",
    "median_gap",
    "gap_std",
    "gap_q25",
    "gap_q75",
    "minimum_gap",
    "maximum_gap",
    "breadth_above_open_at_cutoff",
    "breadth_below_open_at_cutoff",
    "breadth_above_previous_close_at_cutoff",
    "mean_return_from_open",
    "median_return_from_open",
    "return_from_open_std",
    "return_from_open_q25",
    "return_from_open_q75",
    "minimum_return_from_open",
    "maximum_return_from_open",
    "cross_sectional_return_dispersion",
    "mean_opening_range_pct",
    "median_opening_range_pct",
    "opening_range_dispersion_pct",
    "mean_early_realized_volatility",
    "median_early_realized_volatility",
    "breadth_above_open_at_0935",
    "breadth_above_open_at_0940",
    "breadth_acceleration_0935_to_0940",
    "median_return_from_open_at_0935",
    "median_return_from_open_at_0940",
    "median_return_acceleration_0935_to_0940",
    "previous_session_equal_weight_return",
    "previous_session_median_return",
    "previous_session_positive_breadth",
    "previous_session_cross_sectional_dispersion",
    "prior_2_session_market_return",
    "prior_5_session_market_return",
    "prior_10_session_market_return",
    "prior_5_session_realized_volatility",
    "prior_10_session_realized_volatility",
    "prior_5_session_max_drawdown",
    "prior_10_session_max_drawdown",
    "previous_session_pct_above_5d_sma",
    "previous_session_pct_above_10d_sma",
    "consecutive_positive_sessions",
    "consecutive_negative_sessions",
    "v1_valid_candidates",
    "v1_triggered_candidates",
    "v1_completed_trades",
    "v1_realized_pnl_sek",
    "v1_account_return",
    "available_model_feature_count",
    "total_model_feature_count",
    "missing_model_feature_count",
    "feature_completeness_rate",
    "classifier_audit_rows",
    "classifier_audit_pass_rows",
    "classifier_audit_fail_rows",
    "point_in_time_leakage_rows",
    "available_now_feature_count",
    "planned_external_feature_count",
    "diagnostic_only_feature_count",
    "v1_diagnostic_joined_sessions",
    "rows_or_sessions_used",
    "observed_sessions",
    "comparison_eligible_sessions",
    "regime_label_match_sessions",
    "regime_label_match_rate",
    "changed_regime_label_sessions",
    "favorable_gate_match_sessions",
    "favorable_gate_match_rate",
    "changed_favorable_gate_sessions",
    "candidate_rows_compared",
    "candidate_action_match_rows",
    "candidate_action_match_rate",
    "changed_candidate_action_rows",
    "legacy_triggered_trade_rows",
    "strict_triggered_trade_rows",
    "common_triggered_trade_rows",
    "legacy_only_triggered_trade_rows",
    "strict_only_triggered_trade_rows",
    "legacy_portfolio_realized_pnl_sek",
    "strict_portfolio_realized_pnl_sek",
    "strict_minus_legacy_pnl_sek",
    "legacy_sample_size",
    "strict_sample_size",
    "legacy_breadth_above_open",
    "strict_breadth_above_open",
    "breadth_difference_strict_minus_legacy",
    "legacy_median_return_from_open",
    "strict_median_return_from_open",
    "median_return_difference_strict_minus_legacy",
    "candidate_action_mismatches",
    "legacy_trade_pnl_sek_unconstrained",
    "strict_trade_pnl_sek_unconstrained",
    "entry_trigger_difference",
    "stop_price_difference",
    "target_price_difference",
    "legacy_pnl_sek",
    "strict_pnl_sek",
    "pnl_difference_strict_minus_legacy",
    "taxonomy_eligible_sessions",
    "data_limited_sessions",
    "sessions_with_active_response",
    "sessions_without_active_response",
    "no_trade_sessions",
    "regime_definition_count",
    "regimes_observed",
    "regimes_with_active_response",
    "median_regime_confidence",
    "low_confidence_sessions",
    "high_confidence_sessions",
    "point_in_time_safe_sessions",
    "strict_minus_legacy_pnl_sek",
    "prior_percentile_history_count",
    "early_volatility_prior_percentile",
    "opening_range_prior_percentile",
    "return_dispersion_prior_percentile",
    "gap_dispersion_prior_percentile",
    "recovery_score",
    "trend_up_score",
    "trend_down_score",
    "range_low_vol_score",
    "high_vol_reversal_score",
    "high_dispersion_score",
    "volatility_expansion_score",
    "defensive_mixed_score",
    "primary_score",
    "secondary_score",
    "score_margin",
    "regime_confidence",
    "research_risk_multiplier",
    "research_max_concurrent_ideas",
    "strict_v1_triggered_trades_diagnostic",
    "strict_v1_trade_pnl_sek_unconstrained_diagnostic",
    "session_count",
    "session_share",
    "average_confidence",
    "median_confidence",
    "up_bias_sessions",
    "down_bias_sessions",
    "neutral_bias_sessions",
    "transition_count",
    "from_regime_transition_count",
    "transition_probability",
    "average_to_regime_confidence",
    "taxonomy_sessions",
    "sessions_with_mapped_playbook",
    "sessions_without_mapped_playbook",
    "sessions_with_active_simulation_contract",
    "regime_count_expected",
    "regime_count_specified",
    "unique_playbook_count",
    "ready_ohlc_only_playbooks",
    "ready_with_proxy_playbooks",
    "blocked_playbooks",
    "max_concurrent_ideas",
    "taxonomy_sessions",
    "processed_sessions",
    "active_response_sessions",
    "observed_regimes",
    "specified_playbooks",
    "regimes_with_selected_ideas",
    "regimes_with_triggered_trades",
    "candidate_rows",
    "selected_ideas",
    "triggered_trades",
    "closed_trades",
    "sessions_with_triggered_trades",
    "sessions_active_no_trigger",
    "sessions_active_no_valid_setup",
    "single_leg_trades",
    "paired_trades",
    "long_legs",
    "short_legs",
    "gross_pnl_sek_unconstrained",
    "cost_sek_unconstrained",
    "net_pnl_sek_unconstrained",
    "point_in_time_audit_pass_sessions",
    "point_in_time_audit_fail_sessions",
    "execution_invariant_failures",
    "trade_leg_reconciliation_max_abs_diff_sek",
    "input_tickers",
    "valid_setup_candidates",
    "winning_trades",
    "losing_trades",
    "ranking_metric",
    "cutoff_return_from_open",
    "paired_cutoff_return_from_open",
    "opening_gap",
    "early_open",
    "early_high",
    "early_low",
    "early_midpoint",
    "early_range_pct",
    "pair_entry_long_price",
    "pair_entry_short_price",
    "pair_stop_return",
    "pair_target_return",
    "pair_exit_long_price",
    "pair_exit_short_price",
    "gross_return",
    "net_return",
    "notional_sek",
    "gross_pnl_sek",
    "cost_sek",
    "net_pnl_sek",
    "average_net_pnl_sek",
    "median_net_pnl_sek",
    "average_net_return",
    "average_trade_duration_minutes",
    "trade_leg_pnl_difference_sek",
    "source_sessions",
    "source_trades",
    "enriched_trades",
    "single_trades",
    "paired_trades",
    "playbooks_evaluated",
    "playbooks_with_minimum_sample",
    "positive_gross_playbooks",
    "positive_net_playbooks",
    "keep_recommendations",
    "modify_recommendations",
    "invert_recommendations",
    "replace_recommendations",
    "insufficient_sample_recommendations",
    "regime_confidence",
    "actual_mfe_return",
    "actual_mae_return",
    "actual_mfe_pnl_sek",
    "actual_mae_pnl_sek",
    "actual_mfe_r",
    "actual_mae_r",
    "horizon_mfe_return",
    "horizon_mae_return",
    "horizon_close_return",
    "horizon_close_gross_pnl_sek",
    "gross_capture_of_actual_mfe",
    "pair_opposite_same_exit_gross_return",
    "pair_opposite_same_exit_gross_pnl_sek",
    "regime_sessions",
    "sessions_with_trades",
    "winning_trades",
    "losing_trades",
    "target_hit_rate",
    "stop_hit_rate",
    "time_exit_rate",
    "average_actual_mfe_return",
    "average_actual_mae_return",
    "median_actual_mfe_r",
    "median_actual_mae_r",
    "average_gross_capture_of_mfe",
    "stopped_trades",
    "stopped_then_positive_by_cutoff",
    "stopped_then_positive_rate",
    "break_even_round_trip_cost_bps",
    "best_standardized_target_r",
    "best_standardized_target_net_pnl_sek",
    "top_trade_abs_pnl_share",
    "top_day_abs_pnl_share",
    "leave_one_day_out_profitable_share",
    "leave_one_day_out_min_pnl_sek",
    "target_r",
    "scenario_gross_return",
    "scenario_gross_pnl_sek",
    "scenario_cost_sek",
    "scenario_net_pnl_sek",
    "baseline_net_pnl_sek",
    "incremental_net_pnl_sek",
    "scenario_duration_minutes",
    "cost_bps_round_trip",
    "modeled_cost_sek",
    "modeled_net_pnl_sek",
    "omitted_day_net_pnl_sek",
    "remaining_net_pnl_sek",
    "baseline_gross_return_same_exit",
    "baseline_gross_pnl_sek_same_exit",
    "opposite_gross_return_same_exit",
    "opposite_gross_pnl_sek_same_exit",
    "opposite_net_pnl_sek_same_exit",
    "company_observation_weight",
    "previous_close",
    "open_price",
    "cutoff_close",
    "opening_gap_pct",
    "cutoff_return_from_open",
    "early_range_pct",
    "market_return_from_open_company_weighted",
    "sector_return_from_open_company_weighted",
    "economic_cluster_return_from_open_company_weighted",
    "sector_independent_company_count",
    "economic_cluster_independent_company_count",
    "sector_relative_return",
    "economic_cluster_relative_return",
    "market_relative_return",
    "relative_return_used",
    "prior_history_sessions",
    "prior_20d_daily_return_mean",
    "prior_20d_daily_volatility",
    "prior_20d_average_daily_range_pct",
    "prior_20d_average_early_range_pct",
    "prior_20d_average_absolute_gap_pct",
    "prior_20d_gap_volatility",
    "prior_20d_momentum_return",
    "prior_20d_beta_to_company_weighted_market",
    "prior_20d_correlation_to_company_weighted_market",
    "prior_20d_early_move_followthrough_rate",
    "prior_20d_early_move_reversal_rate",
    "prior_20d_early_move_observations",
    "volatility_percentile_cross_section",
    "ticker_count",
    "independent_company_count",
    "observed_ticker_count",
    "effective_company_weight",
    "mean_gap_company_weighted",
    "median_gap",
    "positive_gap_breadth_company_weighted",
    "mean_return_from_open_company_weighted",
    "median_return_from_open",
    "breadth_above_open_company_weighted",
    "cross_sectional_return_dispersion",
    "mean_early_range_pct_company_weighted",
    "group_relative_return_vs_market",
    "same_company_symbol_count",
    "company_weight",
}


def clean_dataframe(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()
    for column in NUMERIC_COLUMNS.intersection(df.columns):
        df[column] = pd.to_numeric(df[column], errors="coerce")
    return df


def excel_sheet_name(logical_name: str) -> str:
    # Excel limits worksheet names to 31 characters. The generated names remain
    # unique because the distinguishing suffix begins before the cutoff.
    return logical_name[:31]


def main() -> None:
    print("\n=== EXPORT REGIME TRADING POWER BI WORKBOOK ===")
    print(f"Output file: {POWERBI_WORKBOOK}")

    missing = [path for path in TABLES.values() if not path.exists()]
    if missing:
        print("The following source files do not exist and will be skipped:")
        for path in missing:
            print(f"- {path}")

    exported = 0
    with pd.ExcelWriter(POWERBI_WORKBOOK, engine="openpyxl") as writer:
        for logical_name, csv_path in TABLES.items():
            if not csv_path.exists():
                continue

            dataframe = clean_dataframe(pd.read_csv(csv_path))
            sheet_name = excel_sheet_name(logical_name)
            dataframe.to_excel(writer, sheet_name=sheet_name, index=False)
            exported += 1
            print(
                f"Exported {logical_name} -> {sheet_name}: "
                f"{len(dataframe)} rows"
            )

        if exported == 0:
            pd.DataFrame(
                [{"status": "No research CSV files have been generated yet."}]
            ).to_excel(writer, sheet_name="status", index=False)

    print(f"\nSaved workbook -> {POWERBI_WORKBOOK}")


if __name__ == "__main__":
    main()
