ORB_STRATEGY_VERSION = "ORB_BEST_BASKET_V1"

ORB_ALLOWED_TICKERS = [
    "SHB-A.ST",
    "ERIC-B.ST",
    "ALFA.ST",
    "SEB-A.ST",
    "ATCO-A.ST",
]

ORB_MAX_OPEN_POSITIONS = 2

ORB_BREAKOUT_START = "09:35"
ORB_BREAKOUT_END = "11:00"

ORB_R_MULTIPLE = 1.0
ORB_MAX_OPENING_RANGE = 0.03
ORB_MIN_GAP = 0.0
ORB_COST_PER_TRADE = 0.0005

ORB_INITIAL_CAPITAL = 10000
ORB_POSITION_SIZE = 0.10